---
kind: pipeline
name: deploy to swarm.autonomic.zone
steps:
  - name: deployment
    image: decentral1se/drone-stack:19.03.8-override-compose
    settings:
      compose: docker-compose.yml
      host: tcp://swarm.autonomic.zone:2376
      override_compose: docker-compose.production.yml
      stack_name: wordpress
      tlsverify: true
    environment:
      PLUGIN_CACERT:
        from_secret: docker_cacert
      PLUGIN_CERT:
        from_secret: docker_cert
      PLUGIN_KEY:
        from_secret: docker_key
trigger:
  branch:
    - master
