---
kind: pipeline
name: deploy to swarm-test.autonomic.zone
steps:
  - name: deployment
    image: decentral1se/stack-ssh-deploy:latest
    settings:
      compose: compose.yml
      host: swarm-test.autonomic.zone
      stack: wordpress
      deploy_key:
        from_secret: drone_ssh_swarm-test.autonomic.zone
    environment:
      DOMAIN: wordpress.swarm-test.autonomic.zone
      STACK_NAME: wordpress
      LETS_ENCRYPT_ENV: production
      DB_PASSWORD_VERSION: v1
      DB_ROOT_PASSWORD_VERSION: v1
trigger:
  branch:
    - master
