---
version: "3.8"

services:
  app:
    entrypoint: /docker-entrypoint.mailrelay.sh
    secrets:
      - smtp_password
    environment:
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT:25}
      - SMTP_AUTH=${SMTP_AUTH}
      - SMTP_TLS=${SMTP_TLS}
      - MAIL_FROM=${MAIL_FROM}
    configs:
      - source: mstmp_conf
        target: /etc/msmtprc
      - source: entrypoint_mailrelay_conf
        target: /docker-entrypoint.mailrelay.sh
        mode: 0555

configs:
  mstmp_conf:
    name: ${STACK_NAME}_mstmp_conf_${MSMTP_CONF_VERSION}
    file: msmtp.conf.tmpl
    template_driver: golang
  entrypoint_mailrelay_conf:
    name: ${STACK_NAME}_entrypoint_mailrelay_${ENTRYPOINT_MAILRELAY_CONF_VERSION}
    file: entrypoint.mailrelay.sh.tmpl
    template_driver: golang

secrets:
  smtp_password:
    name: ${STACK_NAME}_smtp_password_${SECRET_SMTP_PASSWORD_VERSION}
    external: true
