---
version: "3.8"

services:
  app:
    secrets:
      - smtp_password
    environment:
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT:-25}
      - SMTP_AUTH=${SMTP_AUTH}
      - SMTP_TLS=${SMTP_TLS}
      - MAIL_FROM=${MAIL_FROM}

secrets:
  smtp_password:
    name: ${STACK_NAME}_smtp_password_${SECRET_SMTP_PASSWORD_VERSION}
    external: true
