# #############################################################################
# NOTE(decentral1se): this is a test compose.yml to test abra based deployments
# #############################################################################

---
version: "3.8"

services:
  wordpress:
    image: "wordpress:5.5.1"
    networks:
      - backend
      - proxy
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD_FILE=/run/secrets/db_password
      - WORDPRESS_DB_NAME=wordpress
    secrets:
      - db_password
    deploy:
      update_config:
        failure_action: rollback
        order: start-first
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=proxy"
        - "traefik.http.routers.${NAME}.tls=true"
        - "traefik.http.services.${NAME}.loadbalancer.server.port=80"
        - "traefik.http.routers.${NAME}.rule=Host(`${DOMAIN}`)"
        - "traefik.http.routers.${NAME}.tls.certresolver=production"
        - "traefik.http.routers.${NAME}.entrypoints=web-secure"

  mariadb:
    image: "mariadb:10.5"
    volumes:
      - "mariadb:/var/lib/mysql"
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD_FILE=/run/secrets/db_password
    secrets:
      - db_password
      - db_root_password

networks:
  backend:
    driver: overlay
  proxy:
    external: true

volumes:
  mariadb:
  wordpress_content:

secrets:
  db_root_password:
    external: true
    name: ${DB_ROOT_PASSWD}
  db_password:
    external: true
    name: ${DB_PASSWD}
