---
version: "3.8"
 
services:
  wordpress:
    entrypoint: /docker-entrypoint.sh
    environment:
      - SMTP_HOST=${SMTP_HOST}
      - MAIL_FROM=${MAIL_FROM}
    networks:
      - mail
    configs:
      - source: mstmp_conf
        target: /etc/msmtprc
      - source: entrypoint_conf
        target: /docker-entrypoint.sh
        mode: 0555

networks:
  mail:
    external: true

configs:
  mstmp_conf:
    name: ${STACK_NAME}_mstmp_conf_${MSMTP_CONF_VERSION}
    file: msmtp.conf.tmpl
    template_driver: golang
  entrypoint_conf:
    name: ${STACK_NAME}_entrypoint_mailrelay_${ENTRYPOINT_MAILRELAY_CONF_VERSION}
    file: entrypoint.mailrelay.sh.tmpl
    template_driver: golang
